# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(336, 358)
        MainWindow.setMinimumSize(QtCore.QSize(336, 358))
        MainWindow.setMaximumSize(QtCore.QSize(336, 358))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_start = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start.setGeometry(QtCore.QRect(120, 270, 101, 41))
        self.btn_start.setObjectName("btn_start")
        self.groupBox_eq_count = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_eq_count.setGeometry(QtCore.QRect(20, 10, 131, 111))
        self.groupBox_eq_count.setObjectName("groupBox_eq_count")
        self.radioButton_two_eq = QtWidgets.QRadioButton(self.groupBox_eq_count)
        self.radioButton_two_eq.setGeometry(QtCore.QRect(20, 20, 81, 21))
        self.radioButton_two_eq.setObjectName("radioButton_two_eq")
        self.radioButton_three_eq = QtWidgets.QRadioButton(self.groupBox_eq_count)
        self.radioButton_three_eq.setGeometry(QtCore.QRect(20, 60, 82, 17))
        self.radioButton_three_eq.setObjectName("radioButton_three_eq")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 130, 301, 131))
        self.groupBox.setObjectName("groupBox")
        self.inp_dxdt = QtWidgets.QLineEdit(self.groupBox)
        self.inp_dxdt.setGeometry(QtCore.QRect(40, 20, 251, 20))
        self.inp_dxdt.setObjectName("inp_dxdt")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 10, 31, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 31, 31))
        self.label_2.setObjectName("label_2")
        self.inp_dydt = QtWidgets.QLineEdit(self.groupBox)
        self.inp_dydt.setGeometry(QtCore.QRect(40, 60, 251, 20))
        self.inp_dydt.setObjectName("inp_dydt")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 100, 31, 21))
        self.label_3.setObjectName("label_3")
        self.inp_dzdt = QtWidgets.QLineEdit(self.groupBox)
        self.inp_dzdt.setGeometry(QtCore.QRect(40, 100, 251, 20))
        self.inp_dzdt.setObjectName("inp_dzdt")
        self.groupBox_start_cond = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_start_cond.setGeometry(QtCore.QRect(200, 10, 121, 111))
        self.groupBox_start_cond.setObjectName("groupBox_start_cond")
        self.label_4 = QtWidgets.QLabel(self.groupBox_start_cond)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 21, 21))
        self.label_4.setObjectName("label_4")
        self.inp_t0 = QtWidgets.QLineEdit(self.groupBox_start_cond)
        self.inp_t0.setGeometry(QtCore.QRect(40, 20, 61, 20))
        self.inp_t0.setObjectName("inp_t0")
        self.label_5 = QtWidgets.QLabel(self.groupBox_start_cond)
        self.label_5.setGeometry(QtCore.QRect(10, 40, 31, 16))
        self.label_5.setObjectName("label_5")
        self.inp_x0 = QtWidgets.QLineEdit(self.groupBox_start_cond)
        self.inp_x0.setGeometry(QtCore.QRect(40, 40, 61, 20))
        self.inp_x0.setObjectName("inp_x0")
        self.label_6 = QtWidgets.QLabel(self.groupBox_start_cond)
        self.label_6.setGeometry(QtCore.QRect(10, 60, 31, 16))
        self.label_6.setObjectName("label_6")
        self.inp_y0 = QtWidgets.QLineEdit(self.groupBox_start_cond)
        self.inp_y0.setGeometry(QtCore.QRect(40, 60, 61, 20))
        self.inp_y0.setObjectName("inp_y0")
        self.inp_z0 = QtWidgets.QLineEdit(self.groupBox_start_cond)
        self.inp_z0.setGeometry(QtCore.QRect(40, 80, 61, 20))
        self.inp_z0.setObjectName("inp_z0")
        self.label_7 = QtWidgets.QLabel(self.groupBox_start_cond)
        self.label_7.setGeometry(QtCore.QRect(10, 80, 31, 16))
        self.label_7.setObjectName("label_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 336, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RungeKutta4th"))
        self.btn_start.setText(_translate("MainWindow", "Start"))
        self.groupBox_eq_count.setTitle(_translate("MainWindow", "Количество уравнений"))
        self.radioButton_two_eq.setText(_translate("MainWindow", "2 уравнения"))
        self.radioButton_three_eq.setText(_translate("MainWindow", "3 уравнения"))
        self.groupBox.setTitle(_translate("MainWindow", "Система уравнений"))
        self.label.setText(_translate("MainWindow", "dx/dt"))
        self.label_2.setText(_translate("MainWindow", "dy/dy"))
        self.label_3.setText(_translate("MainWindow", "dz/dt"))
        self.groupBox_start_cond.setTitle(_translate("MainWindow", "Начальные условия"))
        self.label_4.setText(_translate("MainWindow", "t0"))
        self.label_5.setText(_translate("MainWindow", "x(t0)"))
        self.label_6.setText(_translate("MainWindow", "y(t0)"))
        self.label_7.setText(_translate("MainWindow", "z(t0)"))
    

    def my_setup_ui(self):
        self.add_functions()
        self.radioButton_two_eq.setChecked(True)
        self.hide_z()

    def add_functions(self):
        self.btn_start.clicked.connect(lambda: self.start_calc())
        self.radioButton_two_eq.toggled.connect(lambda: self.hide_z())
        self.radioButton_three_eq.toggled.connect(lambda: self.show_z())
    
    def hide_z(self):
        if self.radioButton_two_eq.isChecked():
            self.label_3.hide()
            self.inp_dzdt.hide()
            self.label_7.hide()
            self.inp_z0.hide()
    
    def show_z(self):
        if self.radioButton_three_eq.isChecked():
            self.label_3.show()
            self.inp_dzdt.show()
            self.label_7.show()
            self.inp_z0.show()

    def start_calc(self):
        if self.radioButton_two_eq.isChecked():
            dxdt_str = self.inp_dxdt.text()
            dydt_str = self.inp_dydt.text()
            t0_str = self.inp_t0.text()
            x0_str = self.inp_x0.text()
            y0_str = self.inp_y0.text()
            print(dxdt_str, dydt_str, t0_str, x0_str, y0_str)
        if self.radioButton_three_eq.isChecked():
            dxdt_str = self.inp_dxdt.text()
            dydt_str = self.inp_dydt.text()
            dzdt_str = self.inp_dzdt.text()
            t0_str = self.inp_t0.text()
            x0_str = self.inp_x0.text()
            y0_str = self.inp_y0.text()
            z0_str = self.inp_z0.text()
            print(dxdt_str, dydt_str, dzdt_str, t0_str, x0_str, y0_str, z0_str)        



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    ui.my_setup_ui()
    MainWindow.show()
    sys.exit(app.exec_())
